add_newline = false # Add blankline after each prompt

format = """
$fill
$sudo\
$username\
$hostname\
$all\
$directory
${env_var.yazi_level}\
$character
"""
[fill] 
symbol = ""
# symbol = "┄"
style = "#003e3e"

# test commit
[line_break]
disabled = false #New line to write command

[character]
# success_symbol = "[](green)"
success_symbol = '[󰘍](#f16c75 bold)'
error_symbol = "[✗](red)"
vicmd_symbol = "[](green)"

[c]
style = "blue"
symbol = ' '

[nodejs]
disabled = false
style = "green"
not_capable_style = "red"
symbol = ' '


[username]
style_user = '#248CD7 bold'
style_root = '#C94C15 bold'
format = '[$user]($style) '
show_always = true

[hostname]
ssh_only = true
# format = '[@]($style)[$hostname]($style)[\]]($style) '
format = '@(white bold)[$hostname](#04d1f9 bold) '
# format = "$hostname"
style = "#F2CDCD"
disabled = false

[directory]
style = '#2C9F9D bold'
truncation_length = 0
truncate_to_repo = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style="#F9E2AF"
symbol = "󰸏 "
force_display = true

[package]
style="yellow"
symbol = '📦 '
disabled = true

[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
variable = "YAZI_LEVEL"
style = '#F08A3F bold'
symbol = " ->🦆"
format = '[ $symbol ]($style)'
